1. name: CI-SFTP
2.  
3. # Controls when the action will run. 
4. on:
5.   # Triggers the workflow on push or pull request events but only for the main branch
6.   push:
7.     branches: [ main ]
8. #  pull_request:
9. #    branches: [ main ]
10.  
11.   # Allows you to run this workflow manually from the Actions tab
12.   workflow_dispatch:
13.  
14. # A workflow run is made up of one or more jobs that can run sequentially or in parallel
15. jobs:
16.   # This workflow contains a single job called "SFTP"
17.   deploy-via-sftp:
18.     runs-on: ubuntu-latest
19.     steps:
20.       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
21.       - uses: actions/checkout@v2
22.           
23.       - name: SFTP Deploy
24.         uses: wlixcc/SFTP-Deploy-Action@v1.2.1
25.         with:
26.           username: logicism
27.           server: logicism.ddns.net
28.           port: 22 # default is 22
29.           ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
30.  
31.           
32.           # will put all file under this path
33.           local_path: ./* # default is ./*
34.           # files will copy to under remote_path
35.           remote_path: /var/www
36.           
37.           # sftp args
38.           args: '-o ConnectTimeout=5'

From <https://pastebin.com/qDyhc2W4> 
